-- ============================================================
-- POS MANAGER - COMPLETE DATABASE SETUP (v2)
-- Run this in Supabase SQL Editor → New Query → Run All
-- NOTE: If upgrading from v1, run the ALTER TABLE section
-- ============================================================

-- ── 1. CUSTOMERS ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name         TEXT,                        -- Optional: not required for walk-in
  phone        TEXT UNIQUE,                 -- Optional: required only for pending customers
  email        TEXT,
  address      TEXT,
  notes        TEXT,                        -- Free notes about the customer
  total_visits INT DEFAULT 0,               -- Auto-incremented on each bill
  created_at   TIMESTAMP DEFAULT NOW(),
  updated_at   TIMESTAMP DEFAULT NOW()
);

-- ── 2. PRODUCTS ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name         TEXT NOT NULL,
  price        DECIMAL(10,2) NOT NULL,
  cost_price   DECIMAL(10,2) DEFAULT 0,     -- Purchase cost for profit calculation
  stock        INT DEFAULT 0,               -- Current stock count
  unit         TEXT DEFAULT 'pcs',          -- Unit label: kg, litre, pcs, box...
  low_stock_threshold INT DEFAULT 10,       -- Alert when stock <= this value
  category     TEXT,
  barcode      TEXT,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMP DEFAULT NOW(),
  updated_at   TIMESTAMP DEFAULT NOW()
);

-- ── 3. BILLS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bills (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_number     TEXT NOT NULL UNIQUE,    -- Auto-generated by trigger
  customer_id     UUID REFERENCES customers(id) ON DELETE SET NULL,
  total_amount    DECIMAL(10,2) NOT NULL,
  paid_amount     DECIMAL(10,2) DEFAULT 0,
  pending_amount  DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  payment_status  TEXT DEFAULT 'pending', -- 'paid', 'pending', 'partial'
  payment_method  TEXT DEFAULT 'cash',   -- 'cash', 'upi', 'card'
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);

-- ── 4. BILL ITEMS ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bill_items (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_id      UUID REFERENCES bills(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,              -- Snapshot at time of sale
  quantity     INT NOT NULL,
  unit_price   DECIMAL(10,2) NOT NULL,
  cost_price   DECIMAL(10,2) DEFAULT 0,   -- Snapshot for profit calculation
  total_price  DECIMAL(10,2) NOT NULL,
  created_at   TIMESTAMP DEFAULT NOW()
);

-- ── 5. PENDING PAYMENTS ───────────────────────────────────
CREATE TABLE IF NOT EXISTS pending_payments (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id     UUID REFERENCES customers(id) ON DELETE CASCADE,
  bill_id         UUID REFERENCES bills(id) ON DELETE SET NULL,
  amount_due      DECIMAL(10,2) NOT NULL,
  amount_paid     DECIMAL(10,2) DEFAULT 0,
  due_date        DATE,
  reminder_sent   BOOLEAN DEFAULT FALSE,
  last_reminder_at TIMESTAMP,
  status          TEXT DEFAULT 'unpaid',  -- 'unpaid', 'partial', 'paid'
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);

-- ── 6. PAYMENT HISTORY ────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_history (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id    UUID REFERENCES customers(id) ON DELETE SET NULL,
  bill_id        UUID REFERENCES bills(id) ON DELETE SET NULL,
  pending_id     UUID REFERENCES pending_payments(id) ON DELETE SET NULL,
  amount         DECIMAL(10,2) NOT NULL,
  payment_method TEXT DEFAULT 'cash',
  note           TEXT,
  paid_at        TIMESTAMP DEFAULT NOW()
);

-- ── 7. CUSTOMER VISIT HISTORY ─────────────────────────────
-- Tracks every time a customer makes a purchase
CREATE TABLE IF NOT EXISTS customer_visits (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  bill_id     UUID REFERENCES bills(id) ON DELETE SET NULL,
  amount      DECIMAL(10,2) NOT NULL,
  visited_at  TIMESTAMP DEFAULT NOW()
);

-- ── 8. REMINDERS LOG ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS reminders_log (
  id                 UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id        UUID REFERENCES customers(id) ON DELETE SET NULL,
  pending_payment_id UUID REFERENCES pending_payments(id) ON DELETE SET NULL,
  type               TEXT NOT NULL,  -- 'whatsapp', 'sms', 'notification'
  message            TEXT,
  status             TEXT DEFAULT 'sent',  -- 'sent', 'failed'
  sent_at            TIMESTAMP DEFAULT NOW()
);

-- ── 9. DAILY SUMMARY (cache for fast dashboard) ───────────
-- Auto-populated by triggers each day
CREATE TABLE IF NOT EXISTS daily_summary (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  summary_date  DATE NOT NULL UNIQUE,
  total_sales   DECIMAL(10,2) DEFAULT 0,
  total_profit  DECIMAL(10,2) DEFAULT 0,
  total_bills   INT DEFAULT 0,
  customers_visited INT DEFAULT 0,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════
-- AUTO-TRIGGERS
-- ═══════════════════════════════════════════════════════════

-- Auto-update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_bills_updated_at BEFORE UPDATE ON bills FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_pending_updated_at BEFORE UPDATE ON pending_payments FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-generate bill number
CREATE SEQUENCE IF NOT EXISTS bill_number_seq START 1001;

CREATE OR REPLACE FUNCTION generate_bill_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.bill_number IS NULL OR NEW.bill_number = '' THEN
    NEW.bill_number = 'BILL-' || LPAD(nextval('bill_number_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER auto_bill_number BEFORE INSERT ON bills FOR EACH ROW EXECUTE FUNCTION generate_bill_number();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-decrement stock when a bill item is inserted
CREATE OR REPLACE FUNCTION decrement_stock_on_sale()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.product_id IS NOT NULL THEN
    UPDATE products SET stock = GREATEST(0, stock - NEW.quantity) WHERE id = NEW.product_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_decrement_stock AFTER INSERT ON bill_items FOR EACH ROW EXECUTE FUNCTION decrement_stock_on_sale();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-increment customer total_visits when a bill is created
CREATE OR REPLACE FUNCTION increment_customer_visits()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    UPDATE customers SET total_visits = total_visits + 1 WHERE id = NEW.customer_id;
    INSERT INTO customer_visits(customer_id, bill_id, amount) VALUES(NEW.customer_id, NEW.id, NEW.total_amount);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_customer_visits AFTER INSERT ON bills FOR EACH ROW EXECUTE FUNCTION increment_customer_visits();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ═══════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════════
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summary ENABLE ROW LEVEL SECURITY;

-- Phase 1: Allow all for development (you will tighten this later)
-- When you are ready, replace these with auth.uid() based policies
DO $$ BEGIN CREATE POLICY "Allow all" ON customers FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON products FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON bills FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON bill_items FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON pending_payments FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON payment_history FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON customer_visits FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON reminders_log FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON daily_summary FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ═══════════════════════════════════════════════════════════
-- REALTIME
-- ═══════════════════════════════════════════════════════════
ALTER PUBLICATION supabase_realtime ADD TABLE customers;
ALTER PUBLICATION supabase_realtime ADD TABLE bills;
ALTER PUBLICATION supabase_realtime ADD TABLE pending_payments;
ALTER PUBLICATION supabase_realtime ADD TABLE products;

-- ═══════════════════════════════════════════════════════════
-- SAMPLE DATA (remove in production)
-- ═══════════════════════════════════════════════════════════
INSERT INTO products (name, price, cost_price, stock, unit, category, low_stock_threshold) VALUES
('Rice 1kg',     60.00, 45.00, 100, 'kg',    'Grocery', 20),
('Sugar 1kg',    45.00, 35.00,   8, 'kg',    'Grocery', 10),
('Milk 500ml',   30.00, 22.00,  50, 'litre', 'Dairy',   15),
('Bread',        40.00, 28.00,   5, 'pcs',   'Bakery',  10),
('Biscuit Pack', 20.00, 14.00, 200, 'pack',  'Snacks',  20)
ON CONFLICT DO NOTHING;

-- ═══════════════════════════════════════════════════════════
-- SECURITY ROADMAP (for your MCA cybersecurity phase 2)
-- ═══════════════════════════════════════════════════════════
-- When you are ready to secure this for multi-user:
--
-- 1. Add owner_id UUID column to all tables:
--    ALTER TABLE customers ADD COLUMN owner_id UUID REFERENCES auth.users(id);
--
-- 2. Replace "Allow all" policies with:
--    DROP POLICY "Allow all" ON customers;
--    CREATE POLICY "Owner only" ON customers FOR ALL USING (auth.uid() = owner_id);
--
-- 3. Add a trigger to auto-set owner_id on insert:
--    CREATE OR REPLACE FUNCTION set_owner_id()
--    RETURNS TRIGGER AS $$ BEGIN NEW.owner_id = auth.uid(); RETURN NEW; END; $$ LANGUAGE plpgsql;
--    CREATE TRIGGER trg_set_owner BEFORE INSERT ON customers FOR EACH ROW EXECUTE FUNCTION set_owner_id();
--    (repeat for all tables)
--
-- 4. Enable email confirmation in Supabase Auth settings
-- 5. Enable HTTPS-only in Supabase project settings
-- ═══════════════════════════════════════════════════════════
-- ============================================
-- RUN THIS IN SUPABASE SQL EDITOR
-- New columns + tables for enhanced POS
-- ============================================

-- Add cost_price to products (for profit calculation)
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price DECIMAL(10,2) DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INT DEFAULT 10;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit TEXT;

-- Add customer_name to bills (for walk-in display)
ALTER TABLE bills ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS is_pending_sale BOOLEAN DEFAULT FALSE;

-- Customer visits table (track daily visits)
CREATE TABLE IF NOT EXISTS customer_visits (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id),
  customer_name TEXT,
  visit_date DATE DEFAULT CURRENT_DATE,
  bill_id UUID REFERENCES bills(id),
  created_at TIMESTAMP DEFAULT NOW()
);

-- Audit log table
CREATE TABLE IF NOT EXISTS audit_log (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  action TEXT NOT NULL,
  table_name TEXT,
  record_id TEXT,
  old_value JSONB,
  new_value JSONB,
  created_at TIMESTAMP DEFAULT NOW()
);

-- RLS for new tables
ALTER TABLE customer_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON customer_visits FOR ALL USING (true);
CREATE POLICY "Allow all" ON audit_log FOR ALL USING (true);

-- Auto-log visits when a bill is created
-- (handled in application code)

-- Update reminders_log to track sent_at properly
ALTER TABLE reminders_log ALTER COLUMN sent_at SET DEFAULT NOW();
-- ============================================
-- POS MANAGER — SECURITY & BACKUP SQL
-- Run this in Supabase SQL Editor
-- ============================================

-- ── 1. ROW LEVEL SECURITY (RLS) ──────────────
-- Only authenticated users can access data

-- Enable RLS on all tables
ALTER TABLE customers         ENABLE ROW LEVEL SECURITY;
ALTER TABLE products          ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills             ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_items        ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_payments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_history   ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_visits   ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log         ENABLE ROW LEVEL SECURITY;

-- Drop old "allow all" policies
DROP POLICY IF EXISTS "Allow all" ON customers;
DROP POLICY IF EXISTS "Allow all" ON products;
DROP POLICY IF EXISTS "Allow all" ON bills;
DROP POLICY IF EXISTS "Allow all" ON bill_items;
DROP POLICY IF EXISTS "Allow all" ON pending_payments;
DROP POLICY IF EXISTS "Allow all" ON payment_history;
DROP POLICY IF EXISTS "Allow all" ON reminders_log;

-- Create auth-required policies (must be logged in)
CREATE POLICY "auth_read_customers"   ON customers         FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_customers"  ON customers         FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_products"    ON products          FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_products"   ON products          FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_bills"       ON bills             FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_bills"      ON bills             FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_items"       ON bill_items        FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_items"      ON bill_items        FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_pending"     ON pending_payments  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_pending"    ON pending_payments  FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_payments"    ON payment_history   FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_payments"   ON payment_history   FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_reminders"   ON reminders_log     FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_reminders"  ON reminders_log     FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_visits"      ON customer_visits   FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_visits"     ON customer_visits   FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "auth_read_audit"       ON audit_log         FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "auth_write_audit"      ON audit_log         FOR ALL    USING (auth.role() = 'authenticated');

-- ── 2. AUDIT TRIGGER ────────────────────────
-- Auto-logs every INSERT/UPDATE/DELETE to audit_log

CREATE TABLE IF NOT EXISTS audit_log (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  table_name  TEXT NOT NULL,
  action      TEXT NOT NULL,  -- INSERT, UPDATE, DELETE
  record_id   TEXT,
  old_data    JSONB,
  new_data    JSONB,
  changed_by  UUID,           -- auth.uid() of the user
  changed_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION audit_trigger_fn()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO audit_log (table_name, action, record_id, old_data, new_data, changed_by)
  VALUES (
    TG_TABLE_NAME,
    TG_OP,
    COALESCE(NEW.id::TEXT, OLD.id::TEXT),
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN row_to_json(OLD)::JSONB ELSE NULL END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN row_to_json(NEW)::JSONB ELSE NULL END,
    auth.uid()
  );
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Attach audit trigger to critical tables
DROP TRIGGER IF EXISTS audit_customers        ON customers;
DROP TRIGGER IF EXISTS audit_products         ON products;
DROP TRIGGER IF EXISTS audit_bills            ON bills;
DROP TRIGGER IF EXISTS audit_pending_payments ON pending_payments;

CREATE TRIGGER audit_customers        AFTER INSERT OR UPDATE OR DELETE ON customers        FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();
CREATE TRIGGER audit_products         AFTER INSERT OR UPDATE OR DELETE ON products         FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();
CREATE TRIGGER audit_bills            AFTER INSERT OR UPDATE OR DELETE ON bills            FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();
CREATE TRIGGER audit_pending_payments AFTER INSERT OR UPDATE OR DELETE ON pending_payments FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

-- ── 3. INPUT VALIDATION CONSTRAINTS ─────────
-- Database-level validation (second line of defense after app validation)

ALTER TABLE customers
  ADD CONSTRAINT customer_phone_format CHECK (phone ~ '^[0-9]{10,15}$'),
  ADD CONSTRAINT customer_name_length  CHECK (length(name) BETWEEN 1 AND 100),
  ADD CONSTRAINT customer_email_format CHECK (email IS NULL OR email ~* '^[^@]+@[^@]+\.[^@]+$');

ALTER TABLE products
  ADD CONSTRAINT product_price_positive    CHECK (price >= 0),
  ADD CONSTRAINT product_cost_positive     CHECK (cost_price IS NULL OR cost_price >= 0),
  ADD CONSTRAINT product_stock_nonneg      CHECK (stock >= 0),
  ADD CONSTRAINT product_name_length       CHECK (length(name) BETWEEN 1 AND 150),
  ADD CONSTRAINT product_threshold_valid   CHECK (low_stock_threshold IS NULL OR low_stock_threshold > 0);

ALTER TABLE bills
  ADD CONSTRAINT bill_total_positive       CHECK (total_amount > 0),
  ADD CONSTRAINT bill_paid_nonneg          CHECK (paid_amount >= 0),
  ADD CONSTRAINT bill_paid_lte_total       CHECK (paid_amount <= total_amount * 1.01),
  ADD CONSTRAINT bill_method_valid         CHECK (payment_method IN ('cash','upi','card')),
  ADD CONSTRAINT bill_status_valid         CHECK (payment_status IN ('paid','partial','pending','unpaid'));

ALTER TABLE pending_payments
  ADD CONSTRAINT pending_due_positive      CHECK (amount_due > 0),
  ADD CONSTRAINT pending_paid_nonneg       CHECK (amount_paid >= 0),
  ADD CONSTRAINT pending_paid_lte_due      CHECK (amount_paid <= amount_due),
  ADD CONSTRAINT pending_status_valid      CHECK (status IN ('unpaid','partial','paid'));

-- ── 4. PERFORMANCE INDEXES ───────────────────
CREATE INDEX IF NOT EXISTS idx_bills_created_at         ON bills(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bills_customer_id        ON bills(customer_id);
CREATE INDEX IF NOT EXISTS idx_bills_status             ON bills(payment_status);
CREATE INDEX IF NOT EXISTS idx_bill_items_bill_id       ON bill_items(bill_id);
CREATE INDEX IF NOT EXISTS idx_pending_customer_id      ON pending_payments(customer_id);
CREATE INDEX IF NOT EXISTS idx_pending_status           ON pending_payments(status);
CREATE INDEX IF NOT EXISTS idx_customers_phone          ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_products_barcode         ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_products_category        ON products(category);
CREATE INDEX IF NOT EXISTS idx_audit_table_action       ON audit_log(table_name, action);
CREATE INDEX IF NOT EXISTS idx_audit_changed_at         ON audit_log(changed_at DESC);

-- ── 5. BACKUP VIEW ───────────────────────────
-- Easy snapshot view for quick exports

CREATE OR REPLACE VIEW v_bills_summary AS
SELECT
  b.id, b.bill_number, b.created_at,
  c.name AS customer_name, c.phone AS customer_phone,
  b.total_amount, b.paid_amount, b.pending_amount,
  b.payment_status, b.payment_method, b.discount_amount,
  COUNT(bi.id) AS item_count
FROM bills b
LEFT JOIN customers c ON b.customer_id = c.id
LEFT JOIN bill_items bi ON bi.bill_id = b.id
GROUP BY b.id, c.name, c.phone;

CREATE OR REPLACE VIEW v_pending_summary AS
SELECT
  pp.id, pp.created_at,
  c.name AS customer_name, c.phone AS customer_phone,
  b.bill_number, pp.amount_due, pp.amount_paid,
  pp.amount_due - pp.amount_paid AS balance,
  pp.status, pp.last_reminder_at
FROM pending_payments pp
JOIN customers c ON pp.customer_id = c.id
LEFT JOIN bills b ON pp.bill_id = b.id
WHERE pp.status != 'paid';

CREATE OR REPLACE VIEW v_product_sales AS
SELECT
  bi.product_name,
  SUM(bi.quantity) AS total_sold,
  SUM(bi.total_price) AS total_revenue,
  COUNT(DISTINCT bi.bill_id) AS num_bills,
  p.price, p.cost_price, p.stock
FROM bill_items bi
LEFT JOIN products p ON p.name = bi.product_name
GROUP BY bi.product_name, p.price, p.cost_price, p.stock
ORDER BY total_sold DESC;

-- ── 6. DAILY BACKUP FUNCTION ─────────────────
-- Supabase scheduled function for cloud-side backup
-- Enable in Supabase Dashboard → Edge Functions → Schedule

CREATE OR REPLACE FUNCTION create_backup_snapshot()
RETURNS JSONB AS $$
DECLARE
  snap JSONB;
BEGIN
  snap := jsonb_build_object(
    'timestamp', NOW()::TEXT,
    'customer_count', (SELECT COUNT(*) FROM customers),
    'product_count', (SELECT COUNT(*) FROM products),
    'bill_count', (SELECT COUNT(*) FROM bills),
    'total_revenue', (SELECT COALESCE(SUM(paid_amount),0) FROM bills),
    'pending_total', (SELECT COALESCE(SUM(amount_due - amount_paid),0) FROM pending_payments WHERE status != 'paid')
  );
  -- Store snapshot in audit_log as a BACKUP record
  INSERT INTO audit_log (table_name, action, new_data)
  VALUES ('_system', 'BACKUP_SNAPSHOT', snap);
  RETURN snap;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- DONE! Security and backup configured.
-- ============================================
-- ============================================================
-- POS MANAGER - ADD ROLES TO USERS
-- Run this in Supabase SQL Editor -> New Query -> Run All
-- ============================================================

-- 1. Add role column to users table if it doesn't exist
ALTER TABLE users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

-- 2. Make an existing user an admin
-- Replace 'your_email@example.com' with the email of the user you want to make an admin
UPDATE users SET role = 'admin' WHERE email = 'admin@example.com';

-- You can safely run this multiple times.
