-- ============================================================
-- POS MANAGER - COMPLETE DATABASE SETUP (v2)
-- Run this in Supabase SQL Editor → New Query → Run All
-- NOTE: If upgrading from v1, run the ALTER TABLE section
-- ============================================================

-- ── 1. CUSTOMERS ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS customers (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name         TEXT,                        -- Optional: not required for walk-in
  phone        TEXT UNIQUE,                 -- Optional: required only for pending customers
  email        TEXT,
  address      TEXT,
  notes        TEXT,                        -- Free notes about the customer
  total_visits INT DEFAULT 0,               -- Auto-incremented on each bill
  created_at   TIMESTAMP DEFAULT NOW(),
  updated_at   TIMESTAMP DEFAULT NOW()
);

-- ── 2. PRODUCTS ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name         TEXT NOT NULL,
  price        DECIMAL(10,2) NOT NULL,
  cost_price   DECIMAL(10,2) DEFAULT 0,     -- Purchase cost for profit calculation
  stock        INT DEFAULT 0,               -- Current stock count
  unit         TEXT DEFAULT 'pcs',          -- Unit label: kg, litre, pcs, box...
  low_stock_threshold INT DEFAULT 10,       -- Alert when stock <= this value
  category     TEXT,
  barcode      TEXT,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMP DEFAULT NOW(),
  updated_at   TIMESTAMP DEFAULT NOW()
);

-- ── 3. BILLS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bills (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_number     TEXT NOT NULL UNIQUE,    -- Auto-generated by trigger
  customer_id     UUID REFERENCES customers(id) ON DELETE SET NULL,
  total_amount    DECIMAL(10,2) NOT NULL,
  paid_amount     DECIMAL(10,2) DEFAULT 0,
  pending_amount  DECIMAL(10,2) DEFAULT 0,
  discount_amount DECIMAL(10,2) DEFAULT 0,
  payment_status  TEXT DEFAULT 'pending', -- 'paid', 'pending', 'partial'
  payment_method  TEXT DEFAULT 'cash',   -- 'cash', 'upi', 'card'
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);

-- ── 4. BILL ITEMS ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bill_items (
  id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bill_id      UUID REFERENCES bills(id) ON DELETE CASCADE,
  product_id   UUID REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,              -- Snapshot at time of sale
  quantity     INT NOT NULL,
  unit_price   DECIMAL(10,2) NOT NULL,
  cost_price   DECIMAL(10,2) DEFAULT 0,   -- Snapshot for profit calculation
  total_price  DECIMAL(10,2) NOT NULL,
  created_at   TIMESTAMP DEFAULT NOW()
);

-- ── 5. PENDING PAYMENTS ───────────────────────────────────
CREATE TABLE IF NOT EXISTS pending_payments (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id     UUID REFERENCES customers(id) ON DELETE CASCADE,
  bill_id         UUID REFERENCES bills(id) ON DELETE SET NULL,
  amount_due      DECIMAL(10,2) NOT NULL,
  amount_paid     DECIMAL(10,2) DEFAULT 0,
  due_date        DATE,
  reminder_sent   BOOLEAN DEFAULT FALSE,
  last_reminder_at TIMESTAMP,
  status          TEXT DEFAULT 'unpaid',  -- 'unpaid', 'partial', 'paid'
  notes           TEXT,
  created_at      TIMESTAMP DEFAULT NOW(),
  updated_at      TIMESTAMP DEFAULT NOW()
);

-- ── 6. PAYMENT HISTORY ────────────────────────────────────
CREATE TABLE IF NOT EXISTS payment_history (
  id             UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id    UUID REFERENCES customers(id) ON DELETE SET NULL,
  bill_id        UUID REFERENCES bills(id) ON DELETE SET NULL,
  pending_id     UUID REFERENCES pending_payments(id) ON DELETE SET NULL,
  amount         DECIMAL(10,2) NOT NULL,
  payment_method TEXT DEFAULT 'cash',
  note           TEXT,
  paid_at        TIMESTAMP DEFAULT NOW()
);

-- ── 7. CUSTOMER VISIT HISTORY ─────────────────────────────
-- Tracks every time a customer makes a purchase
CREATE TABLE IF NOT EXISTS customer_visits (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id UUID REFERENCES customers(id) ON DELETE CASCADE,
  bill_id     UUID REFERENCES bills(id) ON DELETE SET NULL,
  amount      DECIMAL(10,2) NOT NULL,
  visited_at  TIMESTAMP DEFAULT NOW()
);

-- ── 8. REMINDERS LOG ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS reminders_log (
  id                 UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id        UUID REFERENCES customers(id) ON DELETE SET NULL,
  pending_payment_id UUID REFERENCES pending_payments(id) ON DELETE SET NULL,
  type               TEXT NOT NULL,  -- 'whatsapp', 'sms', 'notification'
  message            TEXT,
  status             TEXT DEFAULT 'sent',  -- 'sent', 'failed'
  sent_at            TIMESTAMP DEFAULT NOW()
);

-- ── 9. DAILY SUMMARY (cache for fast dashboard) ───────────
-- Auto-populated by triggers each day
CREATE TABLE IF NOT EXISTS daily_summary (
  id            UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  summary_date  DATE NOT NULL UNIQUE,
  total_sales   DECIMAL(10,2) DEFAULT 0,
  total_profit  DECIMAL(10,2) DEFAULT 0,
  total_bills   INT DEFAULT 0,
  customers_visited INT DEFAULT 0,
  created_at    TIMESTAMP DEFAULT NOW(),
  updated_at    TIMESTAMP DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════
-- AUTO-TRIGGERS
-- ═══════════════════════════════════════════════════════════

-- Auto-update updated_at timestamps
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_bills_updated_at BEFORE UPDATE ON bills FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER trg_pending_updated_at BEFORE UPDATE ON pending_payments FOR EACH ROW EXECUTE FUNCTION update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-generate bill number
CREATE SEQUENCE IF NOT EXISTS bill_number_seq START 1001;

CREATE OR REPLACE FUNCTION generate_bill_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.bill_number IS NULL OR NEW.bill_number = '' THEN
    NEW.bill_number = 'BILL-' || LPAD(nextval('bill_number_seq')::TEXT, 5, '0');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER auto_bill_number BEFORE INSERT ON bills FOR EACH ROW EXECUTE FUNCTION generate_bill_number();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-decrement stock when a bill item is inserted
CREATE OR REPLACE FUNCTION decrement_stock_on_sale()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.product_id IS NOT NULL THEN
    UPDATE products SET stock = GREATEST(0, stock - NEW.quantity) WHERE id = NEW.product_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_decrement_stock AFTER INSERT ON bill_items FOR EACH ROW EXECUTE FUNCTION decrement_stock_on_sale();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Auto-increment customer total_visits when a bill is created
CREATE OR REPLACE FUNCTION increment_customer_visits()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.customer_id IS NOT NULL THEN
    UPDATE customers SET total_visits = total_visits + 1 WHERE id = NEW.customer_id;
    INSERT INTO customer_visits(customer_id, bill_id, amount) VALUES(NEW.customer_id, NEW.id, NEW.total_amount);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_customer_visits AFTER INSERT ON bills FOR EACH ROW EXECUTE FUNCTION increment_customer_visits();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ═══════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════════
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pending_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_visits ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_summary ENABLE ROW LEVEL SECURITY;

-- Phase 1: Allow all for development (you will tighten this later)
-- When you are ready, replace these with auth.uid() based policies
DO $$ BEGIN CREATE POLICY "Allow all" ON customers FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON products FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON bills FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON bill_items FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON pending_payments FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON payment_history FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON customer_visits FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON reminders_log FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE POLICY "Allow all" ON daily_summary FOR ALL USING (true); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ═══════════════════════════════════════════════════════════
-- REALTIME
-- ═══════════════════════════════════════════════════════════
ALTER PUBLICATION supabase_realtime ADD TABLE customers;
ALTER PUBLICATION supabase_realtime ADD TABLE bills;
ALTER PUBLICATION supabase_realtime ADD TABLE pending_payments;
ALTER PUBLICATION supabase_realtime ADD TABLE products;

-- ═══════════════════════════════════════════════════════════
-- SAMPLE DATA (remove in production)
-- ═══════════════════════════════════════════════════════════
INSERT INTO products (name, price, cost_price, stock, unit, category, low_stock_threshold) VALUES
('Rice 1kg',     60.00, 45.00, 100, 'kg',    'Grocery', 20),
('Sugar 1kg',    45.00, 35.00,   8, 'kg',    'Grocery', 10),
('Milk 500ml',   30.00, 22.00,  50, 'litre', 'Dairy',   15),
('Bread',        40.00, 28.00,   5, 'pcs',   'Bakery',  10),
('Biscuit Pack', 20.00, 14.00, 200, 'pack',  'Snacks',  20)
ON CONFLICT DO NOTHING;

-- ═══════════════════════════════════════════════════════════
-- SECURITY ROADMAP (for your MCA cybersecurity phase 2)
-- ═══════════════════════════════════════════════════════════
-- When you are ready to secure this for multi-user:
--
-- 1. Add owner_id UUID column to all tables:
--    ALTER TABLE customers ADD COLUMN owner_id UUID REFERENCES auth.users(id);
--
-- 2. Replace "Allow all" policies with:
--    DROP POLICY "Allow all" ON customers;
--    CREATE POLICY "Owner only" ON customers FOR ALL USING (auth.uid() = owner_id);
--
-- 3. Add a trigger to auto-set owner_id on insert:
--    CREATE OR REPLACE FUNCTION set_owner_id()
--    RETURNS TRIGGER AS $$ BEGIN NEW.owner_id = auth.uid(); RETURN NEW; END; $$ LANGUAGE plpgsql;
--    CREATE TRIGGER trg_set_owner BEFORE INSERT ON customers FOR EACH ROW EXECUTE FUNCTION set_owner_id();
--    (repeat for all tables)
--
-- 4. Enable email confirmation in Supabase Auth settings
-- 5. Enable HTTPS-only in Supabase project settings
-- ═══════════════════════════════════════════════════════════
